CREATE TYPE "AttendanceStatus" AS ENUM ('PRESENT', 'ABSENT', 'LATE', 'HALF_DAY', 'REMOTE', 'HOLIDAY');
CREATE TYPE "LeaveRequestStatus" AS ENUM ('DRAFT', 'PENDING', 'APPROVED', 'REJECTED', 'CANCELLED');
CREATE TYPE "PayrollStatus" AS ENUM ('DRAFT', 'PROCESSING', 'APPROVED', 'PAID', 'CANCELLED');
CREATE TYPE "LoanStatus" AS ENUM ('ACTIVE', 'PAID', 'DEFAULTED', 'CANCELLED');
CREATE TYPE "RequestStatus" AS ENUM ('PENDING', 'APPROVED', 'REJECTED', 'CANCELLED');
CREATE TYPE "EvaluationStatus" AS ENUM ('DRAFT', 'SUBMITTED', 'APPROVED');
CREATE TYPE "CandidateStatus" AS ENUM ('APPLIED', 'SCREENING', 'INTERVIEW', 'OFFERED', 'HIRED', 'REJECTED');
CREATE TYPE "TrainingStatus" AS ENUM ('PLANNED', 'OPEN', 'COMPLETED', 'CANCELLED');
CREATE TYPE "AssetStatus" AS ENUM ('AVAILABLE', 'ASSIGNED', 'MAINTENANCE', 'RETIRED');
CREATE TYPE "NotificationType" AS ENUM ('INFO', 'SUCCESS', 'WARNING', 'ERROR');

CREATE TABLE "AttendanceRecord" ("id" TEXT NOT NULL, "employeeId" TEXT NOT NULL, "workDate" TIMESTAMP(3) NOT NULL, "checkIn" TIMESTAMP(3), "checkOut" TIMESTAMP(3), "status" "AttendanceStatus" NOT NULL DEFAULT 'PRESENT', "notes" TEXT, "createdAt" TIMESTAMP(3) NOT NULL DEFAULT CURRENT_TIMESTAMP, "updatedAt" TIMESTAMP(3) NOT NULL, CONSTRAINT "AttendanceRecord_pkey" PRIMARY KEY ("id"));
CREATE TABLE "LeaveType" ("id" TEXT NOT NULL, "name" TEXT NOT NULL, "code" TEXT NOT NULL, "description" TEXT, "annualLimit" INTEGER, "isPaid" BOOLEAN NOT NULL DEFAULT true, "isActive" BOOLEAN NOT NULL DEFAULT true, "createdAt" TIMESTAMP(3) NOT NULL DEFAULT CURRENT_TIMESTAMP, "updatedAt" TIMESTAMP(3) NOT NULL, CONSTRAINT "LeaveType_pkey" PRIMARY KEY ("id"));
CREATE TABLE "LeaveRequest" ("id" TEXT NOT NULL, "employeeId" TEXT NOT NULL, "leaveTypeId" TEXT NOT NULL, "startDate" TIMESTAMP(3) NOT NULL, "endDate" TIMESTAMP(3) NOT NULL, "days" DECIMAL(6,2) NOT NULL, "reason" TEXT, "status" "LeaveRequestStatus" NOT NULL DEFAULT 'PENDING', "decidedAt" TIMESTAMP(3), "decisionNote" TEXT, "createdAt" TIMESTAMP(3) NOT NULL DEFAULT CURRENT_TIMESTAMP, "updatedAt" TIMESTAMP(3) NOT NULL, CONSTRAINT "LeaveRequest_pkey" PRIMARY KEY ("id"));
CREATE TABLE "PayrollRun" ("id" TEXT NOT NULL, "name" TEXT NOT NULL, "period" TEXT NOT NULL, "status" "PayrollStatus" NOT NULL DEFAULT 'DRAFT', "paidAt" TIMESTAMP(3), "createdAt" TIMESTAMP(3) NOT NULL DEFAULT CURRENT_TIMESTAMP, "updatedAt" TIMESTAMP(3) NOT NULL, CONSTRAINT "PayrollRun_pkey" PRIMARY KEY ("id"));
CREATE TABLE "PayrollItem" ("id" TEXT NOT NULL, "payrollRunId" TEXT NOT NULL, "employeeId" TEXT NOT NULL, "baseSalary" DECIMAL(12,2) NOT NULL, "allowanceTotal" DECIMAL(12,2) NOT NULL DEFAULT 0, "deductionTotal" DECIMAL(12,2) NOT NULL DEFAULT 0, "overtimeTotal" DECIMAL(12,2) NOT NULL DEFAULT 0, "netPay" DECIMAL(12,2) NOT NULL, "currency" TEXT NOT NULL DEFAULT 'USD', "createdAt" TIMESTAMP(3) NOT NULL DEFAULT CURRENT_TIMESTAMP, "updatedAt" TIMESTAMP(3) NOT NULL, CONSTRAINT "PayrollItem_pkey" PRIMARY KEY ("id"));
CREATE TABLE "Loan" ("id" TEXT NOT NULL, "employeeId" TEXT NOT NULL, "loanNumber" TEXT NOT NULL, "principalAmount" DECIMAL(12,2) NOT NULL, "outstandingAmount" DECIMAL(12,2) NOT NULL, "installmentAmount" DECIMAL(12,2) NOT NULL, "currency" TEXT NOT NULL DEFAULT 'USD', "issuedAt" TIMESTAMP(3) NOT NULL, "status" "LoanStatus" NOT NULL DEFAULT 'ACTIVE', "notes" TEXT, "createdAt" TIMESTAMP(3) NOT NULL DEFAULT CURRENT_TIMESTAMP, "updatedAt" TIMESTAMP(3) NOT NULL, CONSTRAINT "Loan_pkey" PRIMARY KEY ("id"));
CREATE TABLE "OvertimeRequest" ("id" TEXT NOT NULL, "employeeId" TEXT NOT NULL, "workDate" TIMESTAMP(3) NOT NULL, "hours" DECIMAL(6,2) NOT NULL, "rate" DECIMAL(8,2) NOT NULL DEFAULT 1.5, "reason" TEXT, "status" "RequestStatus" NOT NULL DEFAULT 'PENDING', "createdAt" TIMESTAMP(3) NOT NULL DEFAULT CURRENT_TIMESTAMP, "updatedAt" TIMESTAMP(3) NOT NULL, CONSTRAINT "OvertimeRequest_pkey" PRIMARY KEY ("id"));
CREATE TABLE "Allowance" ("id" TEXT NOT NULL, "employeeId" TEXT NOT NULL, "name" TEXT NOT NULL, "amount" DECIMAL(12,2) NOT NULL, "currency" TEXT NOT NULL DEFAULT 'USD', "effectiveFrom" TIMESTAMP(3) NOT NULL, "effectiveTo" TIMESTAMP(3), "isRecurring" BOOLEAN NOT NULL DEFAULT true, "createdAt" TIMESTAMP(3) NOT NULL DEFAULT CURRENT_TIMESTAMP, "updatedAt" TIMESTAMP(3) NOT NULL, CONSTRAINT "Allowance_pkey" PRIMARY KEY ("id"));
CREATE TABLE "Deduction" ("id" TEXT NOT NULL, "employeeId" TEXT NOT NULL, "name" TEXT NOT NULL, "amount" DECIMAL(12,2) NOT NULL, "currency" TEXT NOT NULL DEFAULT 'USD', "effectiveFrom" TIMESTAMP(3) NOT NULL, "effectiveTo" TIMESTAMP(3), "isRecurring" BOOLEAN NOT NULL DEFAULT true, "createdAt" TIMESTAMP(3) NOT NULL DEFAULT CURRENT_TIMESTAMP, "updatedAt" TIMESTAMP(3) NOT NULL, CONSTRAINT "Deduction_pkey" PRIMARY KEY ("id"));
CREATE TABLE "PerformanceEvaluation" ("id" TEXT NOT NULL, "employeeId" TEXT NOT NULL, "period" TEXT NOT NULL, "score" DECIMAL(5,2) NOT NULL, "summary" TEXT, "goals" TEXT, "status" "EvaluationStatus" NOT NULL DEFAULT 'DRAFT', "evaluatedAt" TIMESTAMP(3), "createdAt" TIMESTAMP(3) NOT NULL DEFAULT CURRENT_TIMESTAMP, "updatedAt" TIMESTAMP(3) NOT NULL, CONSTRAINT "PerformanceEvaluation_pkey" PRIMARY KEY ("id"));
CREATE TABLE "JobOpening" ("id" TEXT NOT NULL, "title" TEXT NOT NULL, "code" TEXT NOT NULL, "departmentId" TEXT, "branchId" TEXT, "description" TEXT, "status" TEXT NOT NULL DEFAULT 'OPEN', "openedAt" TIMESTAMP(3) NOT NULL DEFAULT CURRENT_TIMESTAMP, "closedAt" TIMESTAMP(3), "createdAt" TIMESTAMP(3) NOT NULL DEFAULT CURRENT_TIMESTAMP, "updatedAt" TIMESTAMP(3) NOT NULL, CONSTRAINT "JobOpening_pkey" PRIMARY KEY ("id"));
CREATE TABLE "Candidate" ("id" TEXT NOT NULL, "jobOpeningId" TEXT, "firstName" TEXT NOT NULL, "lastName" TEXT NOT NULL, "email" TEXT NOT NULL, "phone" TEXT, "resumeUrl" TEXT, "status" "CandidateStatus" NOT NULL DEFAULT 'APPLIED', "notes" TEXT, "createdAt" TIMESTAMP(3) NOT NULL DEFAULT CURRENT_TIMESTAMP, "updatedAt" TIMESTAMP(3) NOT NULL, CONSTRAINT "Candidate_pkey" PRIMARY KEY ("id"));
CREATE TABLE "TrainingProgram" ("id" TEXT NOT NULL, "title" TEXT NOT NULL, "code" TEXT NOT NULL, "provider" TEXT, "startDate" TIMESTAMP(3), "endDate" TIMESTAMP(3), "status" "TrainingStatus" NOT NULL DEFAULT 'PLANNED', "description" TEXT, "createdAt" TIMESTAMP(3) NOT NULL DEFAULT CURRENT_TIMESTAMP, "updatedAt" TIMESTAMP(3) NOT NULL, CONSTRAINT "TrainingProgram_pkey" PRIMARY KEY ("id"));
CREATE TABLE "TrainingEnrollment" ("id" TEXT NOT NULL, "trainingProgramId" TEXT NOT NULL, "employeeId" TEXT NOT NULL, "status" "TrainingStatus" NOT NULL DEFAULT 'OPEN', "completedAt" TIMESTAMP(3), "score" DECIMAL(5,2), "createdAt" TIMESTAMP(3) NOT NULL DEFAULT CURRENT_TIMESTAMP, "updatedAt" TIMESTAMP(3) NOT NULL, CONSTRAINT "TrainingEnrollment_pkey" PRIMARY KEY ("id"));
CREATE TABLE "Asset" ("id" TEXT NOT NULL, "assetTag" TEXT NOT NULL, "name" TEXT NOT NULL, "category" TEXT NOT NULL, "serialNumber" TEXT, "status" "AssetStatus" NOT NULL DEFAULT 'AVAILABLE', "assignedEmployeeId" TEXT, "assignedAt" TIMESTAMP(3), "returnedAt" TIMESTAMP(3), "createdAt" TIMESTAMP(3) NOT NULL DEFAULT CURRENT_TIMESTAMP, "updatedAt" TIMESTAMP(3) NOT NULL, CONSTRAINT "Asset_pkey" PRIMARY KEY ("id"));
CREATE TABLE "Announcement" ("id" TEXT NOT NULL, "title" TEXT NOT NULL, "body" TEXT NOT NULL, "audience" TEXT NOT NULL DEFAULT 'ALL', "publishedAt" TIMESTAMP(3), "expiresAt" TIMESTAMP(3), "isPublished" BOOLEAN NOT NULL DEFAULT false, "createdAt" TIMESTAMP(3) NOT NULL DEFAULT CURRENT_TIMESTAMP, "updatedAt" TIMESTAMP(3) NOT NULL, CONSTRAINT "Announcement_pkey" PRIMARY KEY ("id"));
CREATE TABLE "Notification" ("id" TEXT NOT NULL, "userId" TEXT, "title" TEXT NOT NULL, "body" TEXT NOT NULL, "type" "NotificationType" NOT NULL DEFAULT 'INFO', "readAt" TIMESTAMP(3), "createdAt" TIMESTAMP(3) NOT NULL DEFAULT CURRENT_TIMESTAMP, CONSTRAINT "Notification_pkey" PRIMARY KEY ("id"));
CREATE TABLE "ReportDefinition" ("id" TEXT NOT NULL, "name" TEXT NOT NULL, "code" TEXT NOT NULL, "description" TEXT, "module" TEXT NOT NULL, "isActive" BOOLEAN NOT NULL DEFAULT true, "createdAt" TIMESTAMP(3) NOT NULL DEFAULT CURRENT_TIMESTAMP, "updatedAt" TIMESTAMP(3) NOT NULL, CONSTRAINT "ReportDefinition_pkey" PRIMARY KEY ("id"));
CREATE TABLE "AppSetting" ("id" TEXT NOT NULL, "key" TEXT NOT NULL, "value" JSONB NOT NULL, "description" TEXT, "isSecret" BOOLEAN NOT NULL DEFAULT false, "updatedAt" TIMESTAMP(3) NOT NULL, "createdAt" TIMESTAMP(3) NOT NULL DEFAULT CURRENT_TIMESTAMP, CONSTRAINT "AppSetting_pkey" PRIMARY KEY ("id"));

CREATE UNIQUE INDEX "AttendanceRecord_employeeId_workDate_key" ON "AttendanceRecord"("employeeId", "workDate");
CREATE INDEX "AttendanceRecord_workDate_idx" ON "AttendanceRecord"("workDate");
CREATE INDEX "AttendanceRecord_status_idx" ON "AttendanceRecord"("status");
CREATE UNIQUE INDEX "LeaveType_code_key" ON "LeaveType"("code");
CREATE INDEX "LeaveRequest_employeeId_idx" ON "LeaveRequest"("employeeId");
CREATE INDEX "LeaveRequest_leaveTypeId_idx" ON "LeaveRequest"("leaveTypeId");
CREATE INDEX "LeaveRequest_status_idx" ON "LeaveRequest"("status");
CREATE UNIQUE INDEX "PayrollRun_period_key" ON "PayrollRun"("period");
CREATE INDEX "PayrollRun_status_idx" ON "PayrollRun"("status");
CREATE UNIQUE INDEX "PayrollItem_payrollRunId_employeeId_key" ON "PayrollItem"("payrollRunId", "employeeId");
CREATE INDEX "PayrollItem_employeeId_idx" ON "PayrollItem"("employeeId");
CREATE UNIQUE INDEX "Loan_loanNumber_key" ON "Loan"("loanNumber");
CREATE INDEX "Loan_employeeId_idx" ON "Loan"("employeeId");
CREATE INDEX "Loan_status_idx" ON "Loan"("status");
CREATE INDEX "OvertimeRequest_employeeId_idx" ON "OvertimeRequest"("employeeId");
CREATE INDEX "OvertimeRequest_status_idx" ON "OvertimeRequest"("status");
CREATE INDEX "Allowance_employeeId_idx" ON "Allowance"("employeeId");
CREATE INDEX "Deduction_employeeId_idx" ON "Deduction"("employeeId");
CREATE UNIQUE INDEX "PerformanceEvaluation_employeeId_period_key" ON "PerformanceEvaluation"("employeeId", "period");
CREATE INDEX "PerformanceEvaluation_status_idx" ON "PerformanceEvaluation"("status");
CREATE UNIQUE INDEX "JobOpening_code_key" ON "JobOpening"("code");
CREATE INDEX "JobOpening_status_idx" ON "JobOpening"("status");
CREATE INDEX "Candidate_email_idx" ON "Candidate"("email");
CREATE INDEX "Candidate_status_idx" ON "Candidate"("status");
CREATE UNIQUE INDEX "TrainingProgram_code_key" ON "TrainingProgram"("code");
CREATE UNIQUE INDEX "TrainingEnrollment_trainingProgramId_employeeId_key" ON "TrainingEnrollment"("trainingProgramId", "employeeId");
CREATE INDEX "TrainingEnrollment_employeeId_idx" ON "TrainingEnrollment"("employeeId");
CREATE UNIQUE INDEX "Asset_assetTag_key" ON "Asset"("assetTag");
CREATE INDEX "Asset_status_idx" ON "Asset"("status");
CREATE INDEX "Asset_assignedEmployeeId_idx" ON "Asset"("assignedEmployeeId");
CREATE INDEX "Announcement_isPublished_idx" ON "Announcement"("isPublished");
CREATE INDEX "Notification_userId_idx" ON "Notification"("userId");
CREATE INDEX "Notification_readAt_idx" ON "Notification"("readAt");
CREATE UNIQUE INDEX "ReportDefinition_code_key" ON "ReportDefinition"("code");
CREATE UNIQUE INDEX "AppSetting_key_key" ON "AppSetting"("key");

ALTER TABLE "AttendanceRecord" ADD CONSTRAINT "AttendanceRecord_employeeId_fkey" FOREIGN KEY ("employeeId") REFERENCES "Employee"("id") ON DELETE CASCADE ON UPDATE CASCADE;
ALTER TABLE "LeaveRequest" ADD CONSTRAINT "LeaveRequest_employeeId_fkey" FOREIGN KEY ("employeeId") REFERENCES "Employee"("id") ON DELETE CASCADE ON UPDATE CASCADE;
ALTER TABLE "LeaveRequest" ADD CONSTRAINT "LeaveRequest_leaveTypeId_fkey" FOREIGN KEY ("leaveTypeId") REFERENCES "LeaveType"("id") ON DELETE RESTRICT ON UPDATE CASCADE;
ALTER TABLE "PayrollItem" ADD CONSTRAINT "PayrollItem_payrollRunId_fkey" FOREIGN KEY ("payrollRunId") REFERENCES "PayrollRun"("id") ON DELETE CASCADE ON UPDATE CASCADE;
ALTER TABLE "PayrollItem" ADD CONSTRAINT "PayrollItem_employeeId_fkey" FOREIGN KEY ("employeeId") REFERENCES "Employee"("id") ON DELETE CASCADE ON UPDATE CASCADE;
ALTER TABLE "Loan" ADD CONSTRAINT "Loan_employeeId_fkey" FOREIGN KEY ("employeeId") REFERENCES "Employee"("id") ON DELETE CASCADE ON UPDATE CASCADE;
ALTER TABLE "OvertimeRequest" ADD CONSTRAINT "OvertimeRequest_employeeId_fkey" FOREIGN KEY ("employeeId") REFERENCES "Employee"("id") ON DELETE CASCADE ON UPDATE CASCADE;
ALTER TABLE "Allowance" ADD CONSTRAINT "Allowance_employeeId_fkey" FOREIGN KEY ("employeeId") REFERENCES "Employee"("id") ON DELETE CASCADE ON UPDATE CASCADE;
ALTER TABLE "Deduction" ADD CONSTRAINT "Deduction_employeeId_fkey" FOREIGN KEY ("employeeId") REFERENCES "Employee"("id") ON DELETE CASCADE ON UPDATE CASCADE;
ALTER TABLE "PerformanceEvaluation" ADD CONSTRAINT "PerformanceEvaluation_employeeId_fkey" FOREIGN KEY ("employeeId") REFERENCES "Employee"("id") ON DELETE CASCADE ON UPDATE CASCADE;
ALTER TABLE "Candidate" ADD CONSTRAINT "Candidate_jobOpeningId_fkey" FOREIGN KEY ("jobOpeningId") REFERENCES "JobOpening"("id") ON DELETE SET NULL ON UPDATE CASCADE;
ALTER TABLE "TrainingEnrollment" ADD CONSTRAINT "TrainingEnrollment_trainingProgramId_fkey" FOREIGN KEY ("trainingProgramId") REFERENCES "TrainingProgram"("id") ON DELETE CASCADE ON UPDATE CASCADE;
ALTER TABLE "TrainingEnrollment" ADD CONSTRAINT "TrainingEnrollment_employeeId_fkey" FOREIGN KEY ("employeeId") REFERENCES "Employee"("id") ON DELETE CASCADE ON UPDATE CASCADE;
ALTER TABLE "Asset" ADD CONSTRAINT "Asset_assignedEmployeeId_fkey" FOREIGN KEY ("assignedEmployeeId") REFERENCES "Employee"("id") ON DELETE SET NULL ON UPDATE CASCADE;
ALTER TABLE "Notification" ADD CONSTRAINT "Notification_userId_fkey" FOREIGN KEY ("userId") REFERENCES "User"("id") ON DELETE CASCADE ON UPDATE CASCADE;
