"use client";
import { useState, useTransition } from 'react';
import Link from 'next/link';
import { Monitor, Moon, Shield, Smartphone } from 'lucide-react';
import { Button } from '@/components/ui/button';

type Props={settings:any; sessions:any[]; user:any};
export function EmployeeSettingsPortal({settings,sessions,user}:Props){const[local,setLocal]=useState(settings||{});const[pending,startTransition]=useTransition();function save(patch:any){const next={...local,...patch};setLocal(next);startTransition(()=>{void fetch('/api/employee/portal-sections',{method:'POST',headers:{'Content-Type':'application/json'},body:JSON.stringify({section:'securitySettings',data:next})})})}return <main className="space-y-6" dir="rtl"><h1 className="text-3xl font-black">الإعدادات</h1><section className="grid gap-4 md:grid-cols-2 xl:grid-cols-3"><Card title="تغيير كلمة المرور" icon={Shield}><Link className="rounded-xl bg-indigo-600 px-4 py-2 text-white" href="/employee/settings/password">تغيير كلمة المرور</Link></Card><Card title="تغيير الصورة" icon={Smartphone}><Link className="rounded-xl border px-4 py-2" href="/employee/settings/profile-picture">تغيير الصورة</Link></Card><Card title="اللغة" icon={Monitor}><Link className="rounded-xl border px-4 py-2" href="/employee/settings/language">اللغة والمنطقة</Link></Card><Card title="الوضع الداكن" icon={Moon}><Button disabled={pending} onClick={()=>save({darkMode:!local.darkMode})}>{local.darkMode?'تعطيل':'تفعيل'}</Button></Card><Card title="2FA" icon={Shield}><Button disabled={pending} onClick={()=>save({twoFactorEnabled:!local.twoFactorEnabled})}>{local.twoFactorEnabled?'مفعل':'غير مفعل'}</Button></Card><Card title="حالة الحساب" icon={Shield}><p>{user?.isActive?'نشط':'غير نشط'}</p><p className="text-xs text-muted-foreground">{user?.mustChangePassword?'يجب تغيير كلمة المرور':'كلمة المرور محدثة'}</p></Card></section><section className="rounded-3xl border p-5"><h2 className="mb-4 text-xl font-black">الأجهزة وجلسات الدخول</h2><div className="space-y-2">{sessions.map(s=><div key={s.id} className="rounded-2xl border p-3"><p className="font-bold">جلسة دخول</p><p className="text-xs text-muted-foreground">تنتهي: {new Date(s.expires).toLocaleString('ar-SA')}</p></div>)}{!sessions.length&&<p className="text-muted-foreground">لا توجد جلسات نشطة مسجلة.</p>}</div></section></main>}
function Card({title,icon:Icon,children}:{title:string;icon:any;children:any}){return <div className="rounded-3xl border bg-card p-5"><Icon className="mb-3 h-6 w-6 text-indigo-600"/><h2 className="mb-3 font-black">{title}</h2>{children}</div>}
