"use client";
import { useMemo, useState, useTransition } from 'react';
import { Button } from '@/components/ui/button';
import { Input } from '@/components/ui/input';
import { Card, CardContent, CardHeader, CardTitle } from '@/components/ui/card';

type Advance = { id:string; amount:any; reason:string; installments:number; monthlyDeduction:any; startDate:string; status:string; managerStatus:string; hrStatus:string; financeStatus:string; notes?:string; createdAt:string };
export function EmployeeAdvancesClient({ initialRecords }: { initialRecords: Advance[] }) {
  const [records,setRecords]=useState<Advance[]>(initialRecords||[]); const [open,setOpen]=useState(false); const [pending,startTransition]=useTransition();
  const [form,setForm]=useState({amount:'',reason:'',installments:'1',startDate:'',notes:''});
  const active=records.filter(r=>!['APPROVED','REJECTED'].includes(r.status));
  const total=records.reduce((s,r)=>s+Number(r.amount||0),0); const monthly=active.reduce((s,r)=>s+Number(r.monthlyDeduction||0),0);
  function submit(){startTransition(async()=>{const res=await fetch('/api/employee/advances',{method:'POST',headers:{'Content-Type':'application/json'},body:JSON.stringify(form)});const json=await res.json();if(json.success){setRecords([json.record,...records]);setOpen(false);setForm({amount:'',reason:'',installments:'1',startDate:'',notes:''})}else alert(json.message||'فشل الطلب')})}
  function remove(id:string){if(!confirm('حذف الطلب؟'))return;startTransition(async()=>{const res=await fetch(`/api/employee/advances?id=${id}`,{method:'DELETE'});const json=await res.json();if(json.success)setRecords(records.filter(r=>r.id!==id));else alert(json.message||'فشل الحذف')})}
  return <main className="space-y-6" dir="rtl"><div className="flex items-center justify-between"><div><h1 className="text-3xl font-black">طلبات السلف</h1><p className="text-muted-foreground">لوحة السلف وسير اعتمادها.</p></div><Button onClick={()=>setOpen(true)}>طلب سلفة جديدة</Button></div><section className="grid gap-4 md:grid-cols-4"><K t="الرصيد المستحق" v={monthly.toLocaleString('ar-SA')}/><K t="السلف السابقة" v={records.length}/><K t="السلف النشطة" v={active.length}/><K t="إجمالي السلف" v={total.toLocaleString('ar-SA')}/></section>{open&&<div className="rounded-3xl border bg-card p-5 shadow-xl"><h2 className="mb-4 text-xl font-black">طلب سلفة جديدة</h2><div className="grid gap-3 md:grid-cols-3"><Input type="number" placeholder="قيمة السلفة" value={form.amount} onChange={e=>setForm({...form,amount:e.target.value})}/><Input placeholder="سبب السلفة" value={form.reason} onChange={e=>setForm({...form,reason:e.target.value})}/><Input type="number" placeholder="عدد الأقساط" value={form.installments} onChange={e=>setForm({...form,installments:e.target.value})}/><Input type="date" value={form.startDate} onChange={e=>setForm({...form,startDate:e.target.value})}/><Input placeholder="ملاحظات" value={form.notes} onChange={e=>setForm({...form,notes:e.target.value})}/><label className="rounded-xl border px-3 py-2 text-sm">مرفقات<input type="file" multiple className="hidden"/></label></div><div className="mt-4 flex gap-2"><Button disabled={pending} onClick={submit}>إرسال</Button><Button variant="outline" onClick={()=>setOpen(false)}>إلغاء</Button></div></div>}<div className="grid gap-3">{records.map(r=><Card key={r.id} className="rounded-3xl"><CardHeader><div className="flex justify-between gap-3"><CardTitle>{Number(r.amount).toLocaleString('ar-SA')} ر.س</CardTitle><Button size="sm" variant="destructive" onClick={()=>remove(r.id)} disabled={r.status!=='PENDING_MANAGER'}>حذف</Button></div></CardHeader><CardContent><p className="text-sm text-muted-foreground">{r.reason}</p><p className="mt-2 text-sm">القسط: {Number(r.monthlyDeduction).toLocaleString('ar-SA')} × {r.installments}</p><Timeline manager={r.managerStatus} hr={r.hrStatus} finance={r.financeStatus} status={r.status}/></CardContent></Card>)}{!records.length&&<div className="rounded-2xl border border-dashed p-6 text-muted-foreground">لا توجد طلبات سلفة.</div>}</div></main>}
function K({t,v}:{t:string;v:any}){return <Card className="rounded-3xl"><CardContent className="p-5"><p className="text-sm text-muted-foreground">{t}</p><p className="text-2xl font-black">{v}</p></CardContent></Card>}
function Timeline({manager,hr,finance,status}:{manager:string;hr:string;finance:string;status:string}){return <div className="mt-4 grid grid-cols-4 gap-2 text-center text-xs"><span className="rounded-xl bg-indigo-50 p-2 text-indigo-700">Employee</span><span className="rounded-xl bg-slate-50 p-2">Manager {manager}</span><span className="rounded-xl bg-slate-50 p-2">HR {hr}</span><span className="rounded-xl bg-emerald-50 p-2 text-emerald-700">Finance {finance}<br/>{status}</span></div>}
