"use client";
import { useMemo, useRef, useState, useTransition } from 'react';
import { Download, Eye, FileText, FolderPlus, Search, Trash2, UploadCloud } from 'lucide-react';
import { Button } from '@/components/ui/button';
import { Input } from '@/components/ui/input';

export function EmployeeDocumentsPortal({ employeeId, initialDocuments }: { employeeId: string; initialDocuments: any[] }) {
  const [docs, setDocs] = useState(initialDocuments);
  const [folders, setFolders] = useState<string[]>([]);
  const [search, setSearch] = useState('');
  const [pending, startTransition] = useTransition();
  const inputRef = useRef<HTMLInputElement>(null);
  const filtered = useMemo(() => docs.filter(d => !search || [d.name,d.fileName,d.type,d.status].some(v => String(v||'').toLowerCase().includes(search.toLowerCase()))), [docs, search]);
  function upload(files?: FileList | File[]) { if (!files?.length) return; startTransition(async()=>{ const form=new FormData(); form.set('employeeId', employeeId); Array.from(files).forEach(f=>form.append('files',f)); const res=await fetch('/api/employees/documents',{method:'POST',body:form}); const json=await res.json(); if(json.success) setDocs((d)=>[...(json.documents||[]),...d]); else alert(json.message||'فشل الرفع'); }); }
  function folder(){ const name=prompt('اسم المجلد'); if(!name) return; startTransition(async()=>{ const res=await fetch('/api/employees/documents',{method:'POST',headers:{'Content-Type':'application/json'},body:JSON.stringify({action:'folder',employeeId,folderName:name})}); const json=await res.json(); if(json.success) setFolders(json.folders||[]); else alert(json.message||'فشل إنشاء المجلد'); }); }
  function del(id:string){ if(!confirm('حذف المستند؟')) return; startTransition(async()=>{ const res=await fetch(`/api/employees/documents?id=${id}`,{method:'DELETE'}); const json=await res.json(); if(json.success) setDocs(d=>d.filter(x=>x.id!==id)); else alert(json.message||'فشل الحذف'); }); }
  return <main className="space-y-6" dir="rtl"><div><h1 className="text-3xl font-black">المستندات</h1><p className="text-muted-foreground">رفع ومعاينة وتنزيل مستنداتك الرسمية.</p></div><div className="flex flex-wrap gap-2"><div className="relative min-w-[260px] flex-1"><Search className="absolute right-3 top-3 h-4 w-4 text-muted-foreground"/><Input value={search} onChange={e=>setSearch(e.target.value)} placeholder="بحث سريع" className="pr-9"/></div><Button disabled={pending} onClick={()=>inputRef.current?.click()}><UploadCloud className="ml-2 h-4 w-4"/>رفع متعدد</Button><Button disabled={pending} variant="outline" onClick={folder}><FolderPlus className="ml-2 h-4 w-4"/>مجلد جديد</Button><input ref={inputRef} className="hidden" type="file" multiple onChange={e=>upload(e.target.files||undefined)} /></div>{folders.length>0&&<div className="flex flex-wrap gap-2">{folders.map(f=><span key={f} className="rounded-full border px-3 py-1">📁 {f}</span>)}</div>}<div onDragOver={e=>e.preventDefault()} onDrop={e=>{e.preventDefault(); upload(e.dataTransfer.files)}} className="rounded-3xl border-2 border-dashed p-10 text-center"><UploadCloud className="mx-auto h-12 w-12 text-muted-foreground"/><p className="mt-3 font-bold">اسحب وأفلت الملفات هنا</p><p className="text-xs text-muted-foreground">PDF, DOC, DOCX, XLS, XLSX, PPT, PPTX, ZIP, RAR, PNG, JPG, WEBP, MP4, MOV, TXT</p><Button className="mt-4" onClick={()=>inputRef.current?.click()}>اختر ملفات</Button></div><div className="grid gap-3 md:grid-cols-2 xl:grid-cols-3">{filtered.map(doc=><div key={doc.id} className="rounded-2xl border p-4"><div className="flex items-center gap-3"><FileText className="h-8 w-8 text-primary"/><div className="min-w-0 flex-1"><p className="truncate font-bold">{doc.fileName||doc.name}</p><p className="text-xs text-muted-foreground">{doc.type} · {doc.status}</p></div></div><div className="mt-3 flex gap-2"><Button size="sm" variant="outline" onClick={()=>window.open(doc.fileUrl,'_blank')}><Eye className="h-4 w-4"/></Button><Button size="sm" variant="outline" onClick={()=>window.open(doc.fileUrl,'_blank')}><Download className="h-4 w-4"/></Button><Button size="sm" variant="destructive" onClick={()=>del(doc.id)}><Trash2 className="h-4 w-4"/></Button></div></div>)}{!filtered.length&&<div className="rounded-2xl border border-dashed p-6 text-muted-foreground">لا توجد مستندات مطابقة.</div>}</div></main>;
}
