import { prisma } from "@/lib/prisma";
import { Button } from "@/components/ui/button";
import { IntegrationShell, DataCard, SimpleTable } from "@/components/integrations/integration-shell";
import { enqueueSync, syncMapping } from "@/lib/integrations/service";

async function runSync(formData: FormData) { "use server"; await syncMapping(String(formData.get("connectionId")), String(formData.get("mappingId")), String(formData.get("direction")) as "HRMS_TO_ODOO" | "ODOO_TO_HRMS" | "BIDIRECTIONAL"); }
async function queueSync(formData: FormData) { "use server"; await enqueueSync({ connectionId: String(formData.get("connectionId")), mappingId: String(formData.get("mappingId")), direction: String(formData.get("direction")) as "HRMS_TO_ODOO" | "ODOO_TO_HRMS" | "BIDIRECTIONAL" }); }

export default async function SynchronizationPage() {
  const [connections, mappings, history, conflicts] = await Promise.all([prisma.integrationConnection.findMany().catch(() => []), prisma.integrationMapping.findMany({ where: { isActive: true } }).catch(() => []), prisma.syncHistory.findMany({ take: 30, orderBy: { startedAt: "desc" } }).catch(() => []), prisma.conflictLog.findMany({ where: { resolution: "PENDING" }, take: 30, orderBy: { createdAt: "desc" } }).catch(() => [])]);
  const form = (action: (formData: FormData) => Promise<void>, label: string) => <form action={action} className="grid gap-3 md:grid-cols-4"><select name="connectionId" className="h-10 rounded-md border bg-background px-3">{connections.map((c) => <option key={c.id} value={c.id}>{c.name}</option>)}</select><select name="mappingId" className="h-10 rounded-md border bg-background px-3">{mappings.map((m) => <option key={m.id} value={m.id}>{m.hrmsModule} ↔ {m.externalModel}</option>)}</select><select name="direction" className="h-10 rounded-md border bg-background px-3"><option value="BIDIRECTIONAL">Both Directions</option><option value="HRMS_TO_ODOO">HRMS → Odoo</option><option value="ODOO_TO_HRMS">Odoo → HRMS</option></select><Button type="submit">{label}</Button></form>;
  return <IntegrationShell title="Synchronization" description="Bidirectional HRMS/Odoo sync with delta, batch, queue, and conflict tracking."><DataCard title="Run Sync Now">{form(runSync, "Run Now")}</DataCard><DataCard title="Queue Background Sync">{form(queueSync, "Queue Job")}</DataCard><DataCard title="Sync History"><SimpleTable columns={["startedAt", "finishedAt", "entity", "direction", "status", "pulled", "pushed", "createdCount", "conflictCount", "error"]} rows={history as unknown as Array<Record<string, unknown>>} /></DataCard><DataCard title="Pending Conflicts"><SimpleTable columns={["createdAt", "entity", "localId", "externalId", "field", "resolution"]} rows={conflicts as unknown as Array<Record<string, unknown>>} /></DataCard></IntegrationShell>;
}
