import dynamic from "next/dynamic";
import { Suspense } from "react";
const NotificationCenterClient = dynamic(() => import("@/components/enterprise/notification-center-client").then((mod) => mod.NotificationCenterClient));
export default function NotificationCenterPage() {
  return <section className="space-y-6"><div className="rounded-2xl border bg-background p-6 shadow-sm"><p className="text-sm font-medium text-muted-foreground">Notifications</p><h1 className="text-3xl font-semibold tracking-tight">Notification Center</h1><p className="mt-2 text-muted-foreground">All, unread, and read notifications generated by requests, approvals, employee changes, and expiry events.</p></div><Suspense fallback={<div className="rounded-xl border bg-card p-8 text-center text-muted-foreground">Loading notifications...</div>}><NotificationCenterClient /></Suspense></section>;
}
