import Link from "next/link";
import { Button } from "@/components/ui/button";
import { Input } from "@/components/ui/input";
import { intelligentAreas, titleFromSlug } from "@/lib/intelligent/catalog";
import { saveIntelligentRecord } from "@/lib/intelligent/actions";

type Row = Record<string, unknown> & { id: string };
export function IntelligentHeader({ title, description }: { title: string; description: string }) { return <div className="rounded-2xl border bg-background p-6 shadow-sm"><p className="text-sm font-medium text-muted-foreground">Phase 6 Intelligent Enterprise Platform</p><h1 className="text-3xl font-semibold tracking-tight">{title}</h1><p className="mt-2 text-muted-foreground">{description}</p></div>; }
export function IntelligentNav(){ return <div className="flex flex-wrap gap-2">{intelligentAreas.map(a=><Link key={a.key} href={`/intelligent/${a.key}/${a.features[0]}`} className="rounded-full border bg-card px-3 py-1.5 text-sm font-medium text-muted-foreground hover:bg-accent hover:text-foreground">{a.title}</Link>)}</div>; }
export function IntelligentFeatureNav({ area }: { area: { key:string; features: readonly string[] } }){ return <div className="flex flex-wrap gap-2">{area.features.map(f=><Link key={f} href={`/intelligent/${area.key}/${f}`} className="rounded-full border bg-card px-3 py-1.5 text-xs font-medium text-muted-foreground hover:bg-accent hover:text-foreground">{titleFromSlug(f)}</Link>)}</div>; }
export function IntelligentForm({ area, feature }: { area:string; feature:string }){ return <form action={saveIntelligentRecord} className="grid gap-3 rounded-2xl border bg-card p-4 md:grid-cols-5"><input type="hidden" name="area" value={area}/><input type="hidden" name="feature" value={feature}/><Input name="code" required aria-label="Code"/><Input name="name" required aria-label="Name"/><textarea name="payload" className="min-h-10 rounded-md border bg-background px-3 py-2 md:col-span-2" defaultValue='{"enabled":true}'/><Button type="submit">Execute</Button></form>; }
export function IntelligentTable({ rows }: { rows: Row[] }){ const keys=Array.from(new Set(rows.flatMap(r=>Object.keys(r)).filter(k=>k!=="id"))).slice(0,9); return <div className="overflow-x-auto rounded-md border bg-card"><table className="w-full text-sm"><thead className="bg-muted/50 text-muted-foreground"><tr>{keys.map(k=><th key={k} className="px-4 py-3 text-start font-medium">{k}</th>)}</tr></thead><tbody className="divide-y">{rows.length===0?<tr><td colSpan={keys.length||1} className="px-4 py-8 text-center text-muted-foreground">No records</td></tr>:rows.map(row=><tr key={row.id}>{keys.map(k=><td key={k} className="max-w-xs truncate px-4 py-3 align-top">{fmt(row[k])}</td>)}</tr>)}</tbody></table></div>; }
function fmt(v:unknown){ if(v instanceof Date) return v.toLocaleString("ar-SA"); if(v===null||v===undefined||v==="") return "—"; if(typeof v==="object") return JSON.stringify(v).slice(0,180); return String(v); }
