import Link from "next/link";
import { Button } from "@/components/ui/button";
import { Input } from "@/components/ui/input";
import { saasSuites, titleFromSlug } from "@/lib/saas/catalog";
import { deleteSaasRecord, saveSaasRecord } from "@/lib/saas/actions";

type Row = Record<string, unknown> & { id: string };

export function SaasHeader({ title, description }: { title: string; description: string }) {
  return <div className="rounded-2xl border bg-background p-6 shadow-sm"><p className="text-sm font-medium text-muted-foreground">Phase 5 Production SaaS Platform</p><h1 className="text-3xl font-semibold tracking-tight">{title}</h1><p className="mt-2 text-muted-foreground">{description}</p></div>;
}
export function SaasNav() { return <div className="flex flex-wrap gap-2">{saasSuites.map((suite)=><Link key={suite.key} href={`/saas-platform/${suite.key}/${suite.features[0]}`} className="rounded-full border bg-card px-3 py-1.5 text-sm font-medium text-muted-foreground hover:bg-accent hover:text-foreground">{suite.title}</Link>)}</div>; }
export function SaasFeatureNav({ suite }: { suite: { key:string; features: readonly string[] } }) { return <div className="flex flex-wrap gap-2">{suite.features.map((feature)=><Link key={feature} href={`/saas-platform/${suite.key}/${feature}`} className="rounded-full border bg-card px-3 py-1.5 text-xs font-medium text-muted-foreground hover:bg-accent hover:text-foreground">{titleFromSlug(feature)}</Link>)}</div>; }
export function SaasForm({ suite, feature }: { suite:string; feature:string }) { return <form action={saveSaasRecord} className="grid gap-3 rounded-2xl border bg-card p-4 md:grid-cols-5"><input type="hidden" name="suite" value={suite}/><input type="hidden" name="feature" value={feature}/><Input name="code" required aria-label="Code"/><Input name="name" required aria-label="Name"/><select name="status" className="h-10 rounded-md border bg-background px-3"><option>ACTIVE</option><option>PENDING</option><option>READY</option><option>CLOSED</option></select><textarea name="payload" className="min-h-10 rounded-md border bg-background px-3 py-2" defaultValue='{"enabled":true}'/><Button type="submit">Save</Button></form>; }
export function SaasTable({ suite, feature, rows, model="saasPlatformRecord" }: { suite:string; feature:string; rows:Row[]; model?:string }) { const keys=Array.from(new Set(rows.flatMap(r=>Object.keys(r)).filter(k=>k!=="id"))).slice(0,8); return <div className="overflow-x-auto rounded-md border bg-card"><table className="w-full text-sm"><thead className="bg-muted/50 text-muted-foreground"><tr>{keys.map(k=><th key={k} className="px-4 py-3 text-start font-medium">{k}</th>)}<th className="px-4 py-3 text-start font-medium">actions</th></tr></thead><tbody className="divide-y">{rows.length===0?<tr><td colSpan={keys.length+1} className="px-4 py-8 text-center text-muted-foreground">No records</td></tr>:rows.map(row=><tr key={row.id}>{keys.map(k=><td key={k} className="max-w-xs truncate px-4 py-3 align-top">{fmt(row[k])}</td>)}<td className="px-4 py-3"><form action={deleteSaasRecord}><input type="hidden" name="suite" value={suite}/><input type="hidden" name="feature" value={feature}/><input type="hidden" name="model" value={model}/><input type="hidden" name="id" value={row.id}/><Button type="submit" variant="destructive" size="sm">Delete</Button></form></td></tr>)}</tbody></table></div>; }
function fmt(v:unknown){ if(v instanceof Date) return v.toLocaleString("ar-SA"); if(v===null||v===undefined||v==="") return "—"; if(typeof v==="object") return JSON.stringify(v).slice(0,180); return String(v); }
